# Generated by Django 5.1.1 on 2025-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coloring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="image URL"
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="images",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="images"
            ),
        ),
    ]
