# Generated by Django 5.1.1 on 2025-02-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_prompt_image_url_alter_prompt_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promts',
            field=models.IntegerField(default=2),
        ),
    ]
