# Generated by Django 5.1.1 on 2025-02-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_user_promts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='promts',
            new_name='prompts_left',
        ),
    ]
