# Generated by Django 5.1.1 on 2025-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0005_rename_promts_user_prompts_left'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='user',
            name='billing_period',
            field=models.CharField(blank=True, default='monthy', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
