# Generated by Django 5.1.1 on 2025-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0007_user_total_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
