# Generated by Django 5.1.1 on 2025-03-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0008_user_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
