# Generated by Django 5.1.1 on 2025-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0010_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.AddField(
            model_name='user',
            name='request_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, default='authenticated', max_length=255, null=True),
        ),
    ]
