# Generated by Django 5.1.1 on 2025-06-10 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0011_delete_visitor_user_request_count_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_count', models.PositiveBigIntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='request_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
