# Generated by Django 5.1.1 on 2025-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0012_visitor_remove_user_request_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='visitor',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
