# Generated by Django 5.1.1 on 2025-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0017_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
