# Generated by Django 5.1.1 on 2025-07-24 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0018_drawing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
