# Generated by Django 5.1.1 on 2025-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0019_drawing_uuid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drawing',
            index=models.Index(fields=['uuid'], name='coloring_dr_uuid_da7e25_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['uuid'], name='coloring_pr_uuid_dd0f74_idx'),
        ),
    ]
